src/http-manager.js
Currently, if the error format isn't correct, the error is displayed as "[Object object]". This modification allows the error to be displayed with the message, even if it isn't the correct format.
=> Request errors with invalid JSON formats display as strings

README.md, package.json, src/http-manager.js, src/spotify-web-api.js, src/webapi-error.js, test/spotify-web-api.js, test/webapi-error.js
Fix for #24.
Responses now include headers, body, and statusCode instead of just the body. Error objects also include statusCode. This is a breaking change so bumping the version to 2.0.0. 
Previous (version 1.x.x):
```javascript
spotifyApi.getArtistTopTracks('0oSGxfWSnnOXhD2fKuz2Gy', 'GB')
.then(function(data) {
console.log(data);
}, function(err) {
console.log('Something went wrong!', err);
});
```
Now (version 2.0.0):
```javascript
spotifyApi.getArtistTopTracks('0oSGxfWSnnOXhD2fKuz2Gy', 'GB')
.then(function(data) {
console.log(data.body);
}, function(err) {
console.log('Something went wrong!', err);
});
```
=> Add headers to response

README.md
* Adds some missing braces for an Object literal in the `removeTracksFromPlaylist` example
=> Fix syntax error in 'removeTracksFromPlaylist' example

src/spotify-web-api.js
`encodeURI` seems to be the way to go for encoding parts of the URL path (`encodeURIComponent` is for query strings)
=> Encode user id to prevent issues with non-ascii chars - Fixes #41

src/http-manager.js, test/http-manager.js
This fixes an issue presented when receiving a JSON string representing the error object. 
An example case is the 429 rate limit error.
```
'{ "error": { "status": 429,  "message": "API rate limit exceeded" } }'
```
This ensures a correct WebApiError is created for these cases.
=> Bug fix case of JSON serialized error object

src/spotify-web-api.js, test/spotify-web-api.js
This was previously proposed in this PR https://github.com/thelinmichael/spotify-web-api-node/pull/44. I think keeping the same signature as the client-side JS wrapper is a good idea.
@thelinmichael
=> Add support for fetching current users playlists

README.md, package.json, src/http-manager.js, test/http-manager.js, test/spotify-web-api.js
Tried to touch the least amount of code as possible, but some of the tests needed to be changed. Mainly the timeout tests were removed, as I couldn't see a way to actually set a timeout on existing requests, and it didn't look like restler had a default timeout.
=> Use superagent instead of restler - Fixes #56

test/spotify-web-api.js
This fixes a reference to restler, which should be now superagent.
@thelinmichael
=> Fix reference to restler, now superagent

.travis.yml, package.json, src/client.js, src/server-methods.js, src/server.js, src/spotify-web-api.js, test/spotify-web-api.js
Fixes #73 
`Promise` is natively supported on Node, and if the library is serialised, it is better to include `Promise` as a polyfill accessible not only by the wrapper but the rest of the app code.
`Buffer` is not needed by the wrapper client-side and it represents a large proportion of the generated bundle.
This PR fixes both issues reducing the size of the bundle to almost half of it.
@thelinmichael
=> Avoid Promise and Buffer to be part of browserified bundle

src/spotify-web-api.js
encodeURI does not encode all valid characters that a username can consist of, such as '#'.
Asking for playlists for a user such as '#matze23' will generate a request error as the # will not be encoded to %23 with encodeURI, even though the username is perfectly valid. Use encodeURIComponent in all username cases to ensure all valid usernames can be requested using the library.
=> Use encodeURIComponent instead of encodeURI

README.md
The refreshAccessToken call is not special; it kind of looked like it updates the access token in the spotifyApi object itself.
(at least, it looked like that to me for a second ;))
=> Make example explicit

src/spotify-web-api.js, test/spotify-web-api.js
Renaming `getMyRecentlyPlayed` to `getMyRecentlyPlayedTracks` to be more consistent with the rest of functions and the same method in [the client-side JS wrapper](https://github.com/JMPerez/spotify-web-api-js).
=> Rename to getMyRecentlyPlayedTracks

src/spotify-web-api.js, test/spotify-web-api.js
According to the following note:
"Note: it is likely that passing a large number of track URIs as a query parameter will exceed the maximum length of the request URI. When adding a large number of tracks it is recommended to pass them in the request body, see below."
https://developer.spotify.com/web-api/add-tracks-to-playlist/
just changed withQueryParameters to withBodyParameters in addTracksToPlaylist
=> change addTracksToPlaylist to request body

src/spotify-web-api.js, test/spotify-web-api.js
I needed to use the "show_dialog" parameter in my personal application to force users to approve the app each time they attempt to log in. This param is not currently supported by the wrapper -- for the time being I can create the auth url manually, but it was an easy addition so I added support for it here.
=> Add support for 'show_dialog' parameter when creating authorization url

README.md, src/spotify-web-api.js, test/spotify-web-api.js
Adds play, pause, next and previous capabilities.
PS: Just now, making the PR, I realised that there where older prs implementing the same :c
=> Playblack control

src/spotify-web-api.js, test/spotify-web-api.js
This PR sets the same method names than the ones used in https://github.com/JMPerez/spotify-web-api-js. This facilitates porting code from client-side to server-side and will make it easier to build an isomorphic library eventually.
=> Unify method names with those from client-side JS wrapper

src/spotify-web-api.js, test/spotify-web-api.js
As pointed out by @brodin, [the extra `deviceIds` in the options is unnecessary](https://github.com/thelinmichael/spotify-web-api-node/pull/121/files/a38a35932ea28689b16830769b556c3f46d6b31d#r136781034).
=> Removes unnecessary deviceIds parameter from request to transfer playback

__tests__/spotify-web-api.js, src/spotify-web-api.js
Even though the requests work without `ids`, it's a good idea to include it so they match the documentation.
=> Add ids key in body when saving/removing tracks - Fixes #193

__tests__/spotify-web-api.js, src/spotify-web-api.js
Support the case in which we don't pass a user but we do pass options when fetching user's playlists.
=> Handle empty user in getUserPlaylists()

__tests__/spotify-web-api.js
This PR doesn't change the library's functionality, but it is good to clarify that the `query` parameter is `q` instead.
=> Rename query to q in tests for consistency

__tests__/spotify-web-api.js, src/spotify-web-api.js
Added support for token based authentication as documented on Spotify's [authorization guide](https://developer.spotify.com/documentation/general/guides/authorization-guide/).
=> Update `createAuthorizeURL` to support `token` response types

README.md
As noted in the [release notes for v4.0.0](https://github.com/thelinmichael/spotify-web-api-node/releases/tag/v4.0.0), functions that operate on playlists do not need the user ID parameter, and as I tested `getPlaylistTracks` is one of them.
I updated the example in the README.
=> Fix documentation example for getPlaylistTracks

README.md, examples/add-remove-replace-tracks-in-a-playlist.js, examples/add-tracks-to-a-playlist.js, src/spotify-web-api.js
The arguments being passed to `createPlaylist` and `addTracksToPlaylist` in the examples are not up to date with the code. I discovered this because I was getting 404s when trying the examples.
=> Documentation fixes

README.md, __tests__/spotify-web-api.js, src/spotify-web-api.js
This pull request add support for the 'Implicit Grant Flow' to support users that want to build fully client-side apps.
It implements the protocol as defined by [spotify](https://developer.spotify.com/documentation/general/guides/authorization-guide/#implicit-grant-flow)
=> Add support for 'Implicit Grant Flow'

__tests__/http-manager.js, __tests__/webapi-error.js, src/http-manager.js, src/webapi-error.js
Fixes #286 
When a request produces an error the Spotify Web API includes a [error object](https://developer.spotify.com/documentation/web-api/reference/object-model/#error-object) in the response. If the request was against a [player endpoint](https://developer.spotify.com/documentation/web-api/reference/player/), this [player error object](https://developer.spotify.com/documentation/web-api/reference/object-model/#player-error-object) will also include a reason string.
The current implementation uses neither of those error objects. Instead the error message will be generic based on the HTTP status code (e.g. `Bad Request` for 400, `Bad Gateway` for 502). Having access to these detail-rich error responses is important for debugging. In the case of the player error responses, it is also …
=> Add support for detailed Spotify Web API error message and reason

__tests__/http-manager.js, src/http-manager.js
This would crash previously if there was a superagent error without a response. Unknown errors will now be forwarded if there's no `error.response`.
=> Fix error handling in http-manager #340
