examples/access-token-using-client-credentials.js

Get access_token from `data.body` not `data`

Fix missing property

---

.coveralls.yml
.gitignore
.travis.yml
README.md
package.json
test/spotify-web-api.js

This adds public visibility for build status and code coverage

Add Travis + Coveralls

---

test/spotify-web-api.js

Implementing some tests that were skipped and fixing some others whose output has changed.

Improve test coverage

---

src/spotify-web-api.js
test/spotify-web-api.js

Add generic Search function to support multiple types

---

README.md
src/spotify-web-api.js
test/spotify-web-api.js

Add functions to make requests to the [new endpoints](https://developer.spotify.com/news-stories/2016/03/29/api-improvements-update/) recently released in the Web API.
@thelinmichael

Add support for audio features, recommendations and user's top tracks and artists

---

src/spotify-web-api.js
test/spotify-web-api.js

Can you review @thelinmichael ?

Encode arrays of seeds as joined strings - Fixes #66

---

src/http-manager.js
test/spotify-web-api.js

Fixes https://github.com/thelinmichael/spotify-web-api-node/issues/72
@thelinmichael

Serialize form data properly in auth endpoints

---

Gruntfile.js
package.json
src/http-manager.js
src/server-methods.js

This PR fixes the linting issues and includes a linting task as part of the build process to prevent errors. Also, it caught an error in the client credentials call.
@thelinmichael

Linting + missing "this."

---

src/spotify-web-api.js

Add Audio-Analysis Endpoint Method

---

examples/access-token-refresh.js
examples/access-token-using-client-credentials.js
examples/add-remove-replace-tracks-in-a-playlist.js
examples/get-info-about-current-user.js
examples/get-top-tracks-for-artist.js

This PR should prevent issues like https://github.com/thelinmichael/spotify-web-api-node/issues/90
@thelinmichael

Remove client ids and secrets from examples

---

README.md

Scrolling through the README this morning, seemed an easy fix!

Make logging for example function in README more accurate

---

src/spotify-web-api.js
test/spotify-web-api.js

Spotify added a new endpoint a few weeks ago (https://developer.spotify.com/web-api/console/get-recently-played/).

Add support for recently played tracks

---

.travis.yml

Set a more up to date list of node versions to make sure we don't miss recent ones.

Update node versions to run the build on travis

---

src/spotify-web-api.js
test/spotify-web-api.js

I am adding to this PR as I need the specific endpoint. This should be ready to merge at any time though 🙂

Adds Connect endpoints

---

src/spotify-web-api.js

Adds `currently-playing` endpoint.

Add currently-playing

---

README.md

This seems missing from the docs, and took me a bit to find. Defined in https://github.com/thelinmichael/spotify-web-api-node/blob/master/src/spotify-web-api.js#L1031

Document getMyCurrentPlaybackState

---

src/spotify-web-api.js
test/spotify-web-api.js

Add missing options (supporting at the moment only `device_id`) for pause

Add options for pause()

---

src/spotify-web-api.js
test/spotify-web-api.js

Adding functions to set volume and seek, following the same method signature as in https://github.com/JMPerez/spotify-web-api-js and including tests.

Add setVolume and seek

---

README.md
__tests__/spotify-web-api.js
package.json
src/spotify-web-api.js

This PR builds on top of @jmfortunatojr's https://github.com/thelinmichael/spotify-web-api-node/pull/235. It adds a fix for jest so tests don't break.

Sept 11 API updates

---

src/spotify-web-api.js

Users can now specify the song’s starting position in ms as an argument to play()'s 'options' field.

Added 'position_ms' for play()

---

README.md
__tests__/spotify-web-api.js
src/spotify-web-api.js

Details here
https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-add-to-queue

added "add song to queue" method 

---

README.md

I've added the missing examples (TBD) from readme file

Completed the TBD examples in README file

---

examples/get-related-artists.js

Included authorization in the example code for get-related-artist.
This is my first PR. Please let me know if anyone has any feedback!

include auth in get-related-artists example #155
